[FEAT]: 계약 조회 화면 구현
ITSM-Project/SLASH-FE pull request #40
Opened 2024-10-29 17:09 UTC by ssooyaa

## 🍀이슈 번호
- closes #33 

## ✅ 구현 내용
- [ ] 계약 조회 화면 구현
- [ ] 서비스카테고리 카드 컴포넌트 구현
- [ ] 계약 생성 후 조회 화면 연결 및 서비스 상세 추가 페이지 연결

## 🐳고민사항 & 기타 & 구현한 화면
<img width="1459" alt="스크린샷 2024-10-30 오전 1 53 20" src="https://github.com/user-attachments/assets/85a4fef0-b49f-420a-851e-5fe86f6413d8">

2024-11-01 08:11 UTC, ssoulistic approved these changes
고생하셨습니다.

2024-11-01 08:16 UTC, ssoulistic approved these changes

2024-11-01 15:33 UTC, Yang-soeun requested changes

2024-11-01 15:33 UTC, Yang-soeun commented on src/components/layout/content/contractManager/contract/contractForm/ContractInfoForm.css
> +}
🍒

2024-11-01 15:33 UTC, Yang-soeun commented on src/components/layout/content/contractManager/contract/contractForm/ContractInfoForm.css
css 개행 하나씩 해주세용

2024-11-01 15:33 UTC, Yang-soeun commented on src/components/layout/content/contractManager/service/serviceForm/ServiceForm.js
> +  // useEffect(() => {
사용 안하는건 지우기~

2024-11-01 15:41 UTC, ssooyaa commented on src/components/layout/content/contractManager/contract/contractForm/ContractInfoForm.css
네~ 확인했습니당~

2024-11-04 01:38 UTC, nyeongha commented on src/components/layout/content/contractManager/contract/contractForm/ContractForm.css
> +  }
여기 공백!

2024-11-04 01:39 UTC, nyeongha commented on src/components/feature/card/ContractServiceCard.css
> +@import "../../../styles/Common.css";
이부분도 한칸 비우는게 좋을것같아요!!

2024-11-04 01:40 UTC, nyeongha commented on src/components/labels/grade/GradeLabel.css
> +@import "../../../styles/Common.css";
여기두 한칸!

2024-11-04 01:43 UTC, nyeongha commented on src/components/layout/content/contractManager/contract/contractContent/ContractStep2
> +import React, { useState } from "react";
여기두 삭제

2024-11-04 01:46 UTC, nyeongha commented on src/components/layout/content/contractManager/service/serviceForm/ServiceForm.js
> +
여기두 한줄 붙여야할것같아용

2024-11-04 01:52 UTC, 6dreamhigh approved these changes
수고하셨습니다!

2024-11-04 01:57 UTC, nyeongha approved these changes

2024-11-04 02:19 UTC, ssooyaa commented on src/components/feature/card/ContractServiceCard.css
> +@import "../../../styles/Common.css";
넹~ 마지막 pr수정하여 푸시 하였습니다!

2024-11-04 04:17 UTC, Yang-soeun approved these changes
수고하셨습니당

2024-11-04 04:17 UTC, merged