Feat/26
ITSM-Project/SLASH-FE pull request #48
Opened 2024-11-03 00:36 UTC by 6dreamhigh

## 🍀이슈 번호
- closes #31 

## ✅ 구현 내용
- [ ] 요청관리 하단 표 api와 연결
- [ ] dropdown 옵션에 따라 필터링 기능
- [ ] 제목, 내용으로 검색되는 기능

## 🐳고민사항 & 기타 & 구현한 화면
- default 요청 관리 화면 
![image](https://github.com/user-attachments/assets/81db46bd-81df-407f-84d5-b17717802c86)
- dropdown 클릭 시 화면 
![image](https://github.com/user-attachments/assets/25f7cdef-fd2c-4127-8d64-a122c6d17833)

- dropdown 옵션과 검색 적용 시 화면
![image](https://github.com/user-attachments/assets/727b5cd2-5ec6-4017-9572-53a4b8b22a5f)

2024-11-03 07:46 UTC, nyeongha commented on src/components/labels/request/RequestLabel.js
> +    }
이 부분 나중에 시간되면 리팩토링할때 요청 타입별 배경색과 글자색을 Map으로 관리하고 Map에 없는 요청 타입들은 자동으로 생성해서 Map에 추가되게끔 해보면 좋을것같아요~!

2024-11-03 07:50 UTC, ssooyaa approved these changes
고생하셨습니다~

2024-11-03 07:58 UTC, nyeongha requested changes

2024-11-03 07:58 UTC, nyeongha commented on src/components/labels/taskType/TaskTypeLabel.js
> +  };
이전 RequestLabel과 비슷한것같은데 가져와서 써도 되지않나용?

2024-11-03 07:58 UTC, nyeongha commented on src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
> +};
이 부분은 동적으로 받는거라 변할 수있어요~!

2024-11-03 07:58 UTC, nyeongha commented on src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
> +  const equipmentTypeOptions = ["전체", "DB", "백업", "서버", "응용프로그램"];
이것도 동적으로 받아요!

2024-11-03 07:58 UTC, nyeongha commented on src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
> +import React, { useEffect, useState } from "react";
혹시 이전 내용이랑 겹친는데 테이블 재사용은 안되나요?

2024-11-03 10:06 UTC, 6dreamhigh commented on src/components/labels/taskType/TaskTypeLabel.js
> +  };
RequestLabel이랑 TaskTypeLabel이랑 같네용. RequestLabel은 삭제하고  TaskTypeLabel로 쓸게요!

2024-11-03 10:12 UTC, 6dreamhigh commented on src/components/labels/request/RequestLabel.js
> +    }
요청 타입은 정해져 있다고 알고 있어서 조건문으로 고정시켰어요!

2024-11-03 10:14 UTC, 6dreamhigh commented on src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
> +import React, { useEffect, useState } from "react";
권한 별로 테이블에 조금씩 다른 컬럼이 들어가 있어 따로 작성했어요

2024-11-03 16:53 UTC, 6dreamhigh commented on src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
> +  const equipmentTypeOptions = ["전체", "DB", "백업", "서버", "응용프로그램"];
상태옵션는 고정되어 있는 값이라 상태옵션을 제외하고 나머지 3항목 모두 db에 있는 값으로 동적으로 받아오는 걸로 수정했습니당

2024-11-03 16:53 UTC, 6dreamhigh commented on src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
> +};
넹 동적으로 처리했어요~!

2024-11-04 04:16 UTC, nyeongha approved these changes

2024-11-04 04:18 UTC, merged