[FEAT]: 로그인 화면 redirection 및 JWT 토큰
ITSM-Project/SLASH-FE pull request #64
Opened 2024-11-04 08:40 UTC by ssoulistic

## 🍀이슈 번호
- closes #59 

## ✅ 구현 내용
- [x] 로그인 연동
- [x] snakecase camelcase로 정정 

### 🚩AXIOS 요청시 추가해야하는 점 
1. 토큰 정보를 가져오고
**const token = localStorage.getItem("accessToken");**

2. 헤더에 "Authorization":{token} 을 추가하여 줍니다.

예시)
```
const token = localStorage.getItem("accessToken");
const response = await axios.post(
        "http://localhost:8080/login",
        { id, password },
        {
          headers: {
            "Authorization":{token},
            "Content-Type": "application/json"
          },
        });

```

## 🐳고민사항 & 기타 & 구현한 화면

2024-11-04 08:56 UTC, 6dreamhigh requested changes

2024-11-04 08:56 UTC, 6dreamhigh commented on src/pages/login/Login.js
> +          redirectUrl = "user";
(세가지 권한 다 포함하는) common 권한도 추가해주세요!

2024-11-04 08:56 UTC, 6dreamhigh commented on src/pages/login/Login.js
>        } else {
useNavigate로 이동하는걸로 수정해주세요!

2024-11-04 08:57 UTC, ssoulistic commented on src/pages/login/Login.js
>        } else {
넵~ 수정하겠습니다~ 👍

2024-11-04 08:58 UTC, ssoulistic commented on src/pages/login/Login.js
>        } else {
넵~ 확인했습니다~

2024-11-04 08:58 UTC, ssoulistic commented on src/pages/login/Login.js
> +          redirectUrl = "user";
common에 해당하는 페이지가 없지 않나요?

2024-11-04 09:07 UTC, 6dreamhigh commented on src/pages/login/Login.js
> +          redirectUrl = "user";
아 백만 설정하면 되겠네요 . 알겠습니당

2024-11-04 09:50 UTC, 6dreamhigh approved these changes

2024-11-04 09:51 UTC, 6dreamhigh commented
충돌 해결해주세요!

2024-11-04 10:23 UTC, ssoulistic commented
> 충돌 해결해주세요!

package-lock. json 에서 이러한 경우가 10개정도 생겼는데,모두 peer:true를 살려두는 쪽으로 처리했습니다.
![image](https://github.com/user-attachments/assets/2d371c60-8621-4449-979a-27d3253c5513)


![image](https://github.com/user-attachments/assets/ea4a169b-e909-4dd1-9fc4-f13f7cfefad5)

2024-11-05 01:36 UTC, ssooyaa approved these changes

2024-11-05 01:36 UTC, merged